
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: depl2
  name: depl2-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: depl2
  template:
    metadata:
      labels:
        app: depl2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: depl2-html-vol
          mountPath: /usr/share/nginx/html

      volumes:
      - name: depl2-html-vol
        configMap:
          name: depl2-cgfmap-html

---
apiVersion: v1
kind: Service
metadata:
  name: depl2-svc
spec:
  selector:
    app: depl2
  ports:
  - name: depl2-svc-http-port
    port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: depl2-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ubuntu-001.dgt.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: depl2-svc
            port:
              number: 80
  tls:
  - hosts:
    - ubuntu-001.dgt.local
    secretName: depl2-secret-tls

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: depl2-cgfmap-html
data:
  index.html: |
    <html>
      <body>
        <h1>Hello, I am nginx SSL.</h1>
      </body>
    </html>


---
apiVersion: v1
kind: Secret
metadata:
  name: depl2-secret-tls
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZ4VENDQTYyZ0F3SUJBZ0lVYngrMTNZNlV3
    VVI1Qi9ZS3BnUk4zMjVPS3Zjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2NqRUxNQWtHQTFVRUJoTUNV
    bFV4RXpBUkJnTlZCQWdNQ2t0b1lXSmhjbTkyYzJzeEV6QVJCZ05WQkFjTQpDa3RvWVdKaGNtOTJj
    MnN4RERBS0JnTlZCQW9NQTBSSFZERU1NQW9HQTFVRUN3d0RUM0puTVIwd0d3WURWUVFECkRCUjFZ
    blZ1ZEhVdE1EQXhMbVJuZEM1c2IyTmhiREFlRncweU5EQXpNekF4T0RJNU5URmFGdzB5TlRBek16
    QXgKT0RJNU5URmFNSEl4Q3pBSkJnTlZCQVlUQWxKVk1STXdFUVlEVlFRSURBcExhR0ZpWVhKdmRu
    TnJNUk13RVFZRApWUVFIREFwTGFHRmlZWEp2ZG5Ock1Rd3dDZ1lEVlFRS0RBTkVSMVF4RERBS0Jn
    TlZCQXNNQTA5eVp6RWRNQnNHCkExVUVBd3dVZFdKMWJuUjFMVEF3TVM1a1ozUXViRzlqWVd3d2dn
    SWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUMKRHdBd2dnSUtBb0lDQVFERldRSE03T1BPRXBJOXZZ
    TURpWlZ4eGhGL3JkY242YnhkTWNBL0FnRitGSWxVeHFtRQpzTk4weEVIVUFmTGl0bG9MQUxyVzBo
    YWlqWDJqMnhEb3RubEFIVEx3TitWWUtjNWNpL0hZNXgwZFhvNGx1d0hQClNCNWs1Y1EwZzJUc1Vo
    dVRuU2JXYWN3ZityYkVmbCs2OFpEUmZyWlNNdjE2V3RWRlhsVXZQU1EvQWcvMmVVNTAKYm9xT2wx
    NTl1b1hhUEdWdW95YVBtajZUa3BGUFhYUGRubDh4dkk2alRJT2ZaRWVVUkt4a3RJa1pUVWZJNS95
    dwpXcWdNWDZiNWJ4RzJidFBzbFVPeVpkZWkvZERCbFNSelRXN0JSeGVQWmRzSjZmMXVuQVJYempP
    QnJqV1MyZDZaCmRSU3JDaE9ybjkxUWdxUTZ1ZHd6NlFlNStBaWdCTWNVQ2U5aVZ3Vkw0TWlyRTVM
    dC9LRXplL0VQVDBmWVhVY3gKdFVjMkZXU3E3UTlpbmpJamVsZzdDci9TVFlscVBHaTdIKzdjYi9P
    ZlVwVEZ0eSt0bWMvTXpOc3h0RE0ya2dBbgp0UVJzKzR4U2FkeXpHRXpua2MxSmp3eXlwcTBBNGt1
    LzJtaVRaQ3ltb01RekFCT3IzTzdlWTFma2pPWG1nNGpiCmlVaWNFNnN3eWtZTVlIblhHdkFmaFlX
    aWdVMG1zOWc0ang3S0xOR1JCVDdRWkR5TUdVQ0U5U1duaTdGcWlRT20KMjBhbnZhZXVJSE5PYzhO
    ankyRTA1MGJhVDBWQWNjcHhBVjZzWGMxNjFIeWVsT1BGNFVFTXFMU2Z3MVlXNUxHSAplUHB3MnVY
    VzJ0VUxETmhhRGJ2MmgyOVBuZlRRdy9SbUhtMzB2YnRFU2t0dDdnQmZlL0xMWGlCcEl3SURBUUFC
    Cm8xTXdVVEFkQmdOVkhRNEVGZ1FVcmpTdkwyMlU2T1EzWjZsbzVra1ZoNTdmTmhFd0h3WURWUjBq
    QkJnd0ZvQVUKcmpTdkwyMlU2T1EzWjZsbzVra1ZoNTdmTmhFd0R3WURWUjBUQVFIL0JBVXdBd0VC
    L3pBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FnRUFJKzNYVnVnVTlpVjZKeFhLNDdDS040c1pDMFdB
    cEdZNFR0ZFp1bW9WdVhTMFB2NFdSVlZBCmdJWEx2YkdBZWhhbkU0T2cyRUtrc004cmZ0V1RkSW92
    aE16MGFqL013NEo5WnEwbnBYaHN3c0VGZ2UxYmVIRXcKWkRVNFdnRGpOa0pQeGFNYTVNVmlob3A0
    K2FPbENDOXcvdm85WWtHc2RMYW5oYTB4L08zU21Pd3lPRDg1akxNVwpzTHBGL2xSYXBKRlFqbDJQ
    QlpBSHZVZXA0UENuV3htR3NnTVArSHFDSlRmVkV3R3Z6dy8yelNoTGN3V1l3RGJzClJraW1GVjR0
    K1JQcW03VS9UeEJuWEY2dXIxZWtYQzdWL2oxcUVHZXFhUDlramIrRjFvVnhXVVFYWHh3azlaQjIK
    KzM3bFptU1lJcVFJSFNaREJJbzR0T05FSVNtcFNTY3FWMTlLUDhqWEl3UE9MZGJPc3Vyb2JQT25U
    VnpsclNtQwo1eXUyUmRXbmVzdG4rYnJDRlFUNkxIWGdQd0FBaDByTGF6UmljN3VqVVVScjlXM2pH
    QnNUeUhYMGF5eERjeG85CkFVb0ZwdDlOMmd5UEFNUERVc1VWU0tPL3pxQ2ZmMzMzU1YzQldMTWhS
    aVp2M1BXa0tmaFlsYU1MbFErWkV6NmIKU0piQldIRjlpM09Yc3FtNys2cjBPRzJoVW9PMVQvUGtI
    S1VQcWgzSGd1RnhQRDh3L1ZRME8yeTJVdkhpb0hqVwpEWDBiWjZUZUdxcGNvVzBCMmJqL1M1TmNo
    cDdTOUhtY3k4UEFLZEtpYndiWkk3MFN0SXJnSVFCK09LNlN2QXlzCk5tZGo5ODJ5bDdraEFxTlhI
    bms4dnhpWnhZWVk4ZDI1WncyREZDejZic2kxQnIza29OWW9mQ2s9Ci0tLS0tRU5EIENFUlRJRklD
    QVRFLS0tLS0K
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQ1N3d2dna29BZ0VBQW9JQ0FRREZXUUhNN09QT0VwSTkKdllNRGlaVnh4aEYvcmRjbjZieGRN
    Y0EvQWdGK0ZJbFV4cW1Fc05OMHhFSFVBZkxpdGxvTEFMclcwaGFpalgyagoyeERvdG5sQUhUTHdO
    K1ZZS2M1Y2kvSFk1eDBkWG80bHV3SFBTQjVrNWNRMGcyVHNVaHVUblNiV2Fjd2YrcmJFCmZsKzY4
    WkRSZnJaU012MTZXdFZGWGxVdlBTUS9BZy8yZVU1MGJvcU9sMTU5dW9YYVBHVnVveWFQbWo2VGtw
    RlAKWFhQZG5sOHh2STZqVElPZlpFZVVSS3hrdElrWlRVZkk1L3l3V3FnTVg2YjVieEcyYnRQc2xV
    T3laZGVpL2REQgpsU1J6VFc3QlJ4ZVBaZHNKNmYxdW5BUlh6ak9CcmpXUzJkNlpkUlNyQ2hPcm45
    MVFncVE2dWR3ejZRZTUrQWlnCkJNY1VDZTlpVndWTDRNaXJFNUx0L0tFemUvRVBUMGZZWFVjeHRV
    YzJGV1NxN1E5aW5qSWplbGc3Q3IvU1RZbHEKUEdpN0grN2NiL09mVXBURnR5K3RtYy9Nek5zeHRE
    TTJrZ0FudFFScys0eFNhZHl6R0V6bmtjMUpqd3l5cHEwQQo0a3UvMm1pVFpDeW1vTVF6QUJPcjNP
    N2VZMWZrak9YbWc0amJpVWljRTZzd3lrWU1ZSG5YR3ZBZmhZV2lnVTBtCnM5ZzRqeDdLTE5HUkJU
    N1FaRHlNR1VDRTlTV25pN0ZxaVFPbTIwYW52YWV1SUhOT2M4Tmp5MkUwNTBiYVQwVkEKY2NweEFW
    NnNYYzE2MUh5ZWxPUEY0VUVNcUxTZncxWVc1TEdIZVBwdzJ1WFcydFVMRE5oYURidjJoMjlQbmZU
    UQp3L1JtSG0zMHZidEVTa3R0N2dCZmUvTExYaUJwSXdJREFRQUJBb0lDQUNFVlB6NkYxZGlsZDF1
    ZlNmZk5XRDYyCitCY0I0d2cvWUVMMVJLZXJZK21wY3E1Q0VZZjdocTlUK1Q4YnhvWm9FR2M0eTVt
    WXBZL0JqWGJyRWdZWkZQR0IKRTVsK25WVnV5TGZ1QS9DYktkL1RDcHhib2IySWR3UHVHcnE4N2kz
    SncvSzJqUnl6cHJNVHVoRHRxSW16MWxXdwpXc3NqM2lkbFU4eHB1SGtQVkdTMXFVeGw0SmVYTW1Z
    ZURRcWh1cSt2b1VkdlZWY01nZ0lHTjVMbzlUUUpTU2NTCjE0eWJscE1oWWZpQ25LM1RNQXFNVUlU
    bkV3N1RXOG1iUFdnaVRRTmF4KzhveEswQzhxZlJ5ZTJ4M1didzY2aSsKREw2TzBpM3l5bmdBOHA5
    dm8yWFJlUXl4dG1YZVlVVWREdGdlR0NGWGpVV0ZBOXUxN0lRcUJ2UWdhT2s4a3lNSwo1YUJESmRP
    WXFNQjIzczRDb2hocU5rOHBhZjRVMkFWTXI0QVcvcTdweDdXcXMyQ1RKOVZlSVk2WHg0UVdnR0gw
    Cjh4aDluMnpHcDF0L1FkOFJMbG5QUjUvUEpjOWdvbDZWSGFBdHBQVlBqS3VMaTR3ZXRQWnRTRDVY
    L3NxRDFXT0wKbzhhZjFEZ2dQMEtzcndXd3FRT2ZFMXZad05zL09vQ3dGTEpLOGhaNENJbXptN3hl
    TE52QjlSYUVKWnQxNDFLcgpldUxMeGtQMG9zcUZES28vTndSVDROb1RoTmFrREdvbDdMb3FCN25T
    T1NvQVJIQjlDaHg0VFlrQjJmM1lDNUlyCmRsNHFHcTcrajBaWCttQ1c4b2EzRHlQUXBkS09JZEps
    dHlWOHE3dUNoMW1XUXlObXRwRjBtaGY1TUh3THZTNEQKRm9GWlc0U3RIdlFSMWJWejl0aVpBb0lC
    QVFEN0d5dFBra0krc0JJTVFEVi9pOERnS1IwM2w3bFdSK0pGVU1zeApQMUdwUllOOVR2UTNaa3pD
    bDM1alBPTS90S1dZTk1XRngrNWl0cHRaYzZDL2M1a0g1V2V5bGFjUUo4VGhDK2tGClRiNHI2Z0Q0
    b2Juc2ovYlRCdHV4TUJRaUhpL1lSNENzUFJZWVFvMU01V3IxckZSQ2JFNkVVanFRYUI0RmdtcHgK
    STBHUUVHSXlCRXhLbmltK3E3NkNCenArTGFQWW1VckhEaUxBaml5NXJPU1BBSmJWV0hZWlJOR29P
    SXR1T0pFWAoxM0FZNGswQkJTOFlnM1E4UERCTndtN3F3NTZiN2R6U1l6WDZxSExHVUlxNHFjR2Y5
    K1FkNXQyL3NQa2xTMzlGCkZHb2VuSkdzSmgvWlhTV3BTSFFJVTJGcWR2Z3JwNkhzaGtWazB1cTdr
    dFZWVVVHYkFvSUJBUURKTVorbGNwcFAKOGFvTVNaK3A0aDVxSGQ4d2JIcWZuQXg3am9hVk9DckRp
    TWV2TDN3Q2xXZlBvNW11RmFiZmI1TkNmTmJxelhZQwptY0p4RXhSMVk0VFVOWUN6dkNOYndvcmZV
    ck1FeVd1NW1mNmE5bE5LUGtKOXRiSXJ3ZDREVEw2L1IxaDFWMVdvCkhSdFpMbGIvSEw1R0pESXox
    YWtMU25JS29iOGZHRmYxaE9aeE1GVGhkK3NPdkhqY2VPOHFRNUN1U2kvSjBtaE0KQkF4QzRIU3RS
    dytZcFZCMzFUNjE0UTJLZm9CNlNYU0xmSFQvMDJPd2J5MEY1NjA2c1J6clBuQUhwZ0J4L3VtbQp0
    QTBSTkw1eGttSnE4L2gxVUx2c1ZOYUZoLy9RS2V4UTRnajFUSDV0L2piS2N6eSt5WXVvdDNZYXBU
    WHl5LzhhClZJUXJrK2VZWDVNWkFvSUJBQUVGNUZCSHJVTnFIamkwamtNOXc0Um1SbnN5Z0F2TThT
    d05IemJOSmowRlRuclYKTm9OL1JETEt3VFlRU25DNUFLKzFEMVR6TXBKdVlnV2tSZlJodVM3aURX
    RVo0UHRjM2gxNG1mTnVsS2JESmt2ZApCTS9rNmtHRDFxTkxLZG5WdTZZcTdHaEhPMjdQM3BtQW1j
    WDBkTWRzZjRsa2VGNmNQZnNSdy9OQURJVlV1OEd1CmFNMHBCY3lFRUp1aEFlai9zSm95VGE2djdR
    NVJ4ZmJmc0hLd3N1eWRscVdWdFREMVFnUXA4TlZqQ0U3aHBTU3EKNjcweTArZG02MTkxdWxQMGho
    SG1qeTdBUHJrTnRLSUFOQUI2bUpKWlJUR2wvaU5JeWtzUG1xNGlYaWhQeFB3cApqNW1vR240dEVH
    UDBTd0pQQjhYTndnZ2ZwK3E0UFVLVVg1QWdhNThDZ2dFQkFJVGZZd0lQUjk1WVNlZkhqOHpRCmF5
    bkdCS3FrV2UralRaTWtNN25FMkdrK29qSU9lQ1gwcWhTMWhUODFTWG55NUJ4YStrMGoyRFlyZWdE
    WGl3RmoKOGt0NzhqM0JtTkIzRU9RZ1o5NVhiKytweGo1dFErQ2FjYXM0SGkxTDRlWG4vMm13SXJt
    TUxpUFM1VWJtbGNueQpINitQSkNDYmtRTEY3YjhieDI4djBwZHhhQWVFMWVuNkdxRW0wK00zY3l4
    RVp2N1VPKzljS0VsYnV3VkgyNGE4CmtZNU1UM0owd08rNWJBbjFOY0NOVm96d2F3eXhmUHIrMFlz
    KzBHY2NwVzZ2VTZtWmRsM1M3bGlNUEwwS1NtUVQKT3pCTFkrR0dxaldRYWdUU0pwNUJzYkpSTlgx
    YlFYdy9FY3h1Z3NXMXNhaUJVVnlUazZlQUZrQTdaUGFxdlo4aQpMN0VDZ2dFQUZGWW9qMWxvaUpP
    dlBBUE45R0VteVhTVmhZaWNTWW9UWGk5RGVDNldsWk9jWUJvOFFDd1hhN3ZLClc0YkJUTmllZys5
    T1VVaHErVm5ZUXZ4S3ExcHo5d01Ycm10S2JKUWtTM2NrMlVXR29GVjIzcXB6dWl5SDgrSmIKSC9n
    dFRUb2pXL0NaMUowcEp0NFkzbUYxcElzU0JSSGU5UFBCSWoxdWM4RGgzN2VjNkVHd2c5R0NuVm5R
    b255NApvaEVCSXNSdE1LbTBpejlVdUplTHdXMmxoVzY0UnpNQkxEcGlNb1hZMkQvU1BtZHUyZyt5
    d2JBNVNHeUZremlTCktVUnVLV3drcFJMbFhVODBCSFY2VVJkQ1AyZXJubnhGRnVxNW43Um5BZHZy
    RjhvUS82aW1aN09JVytZSWlibmoKN1VmdXpIZXdzM25vRkJielZJTUFRSnZ1NFpYY1FnPT0KLS0t
    LS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
       
  
